### PR TITLE
Feature/amp/amp 10 image

### PR DESCRIPTION
**Pull request by paigekeenan**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes AMP-10` 
| Patch: Bug Fix?          |
| Minor: New Feature?      |
| Major: Breaking Change?  |
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  |
| License                  | Apache License, Version 2.0

Fixes: https://bounteous.jira.com/secure/RapidBoard.jspa?rapidView=688&modal=detail&selectedIssue=AMP-10

This creates an AMP image component. The image container has a set height of 200px and width of 100% declared in the CSS. This allows the image to appear as it is set to `layout=fill` and will not display without explicit dimensions. This width and height can be overrode on the component level if needed.

This also deletes the AMP image that was created in Core and moves it into the Component Examples directory.

### CODE REVIEW

**Comment by gaetanmarmasse** [comment]
@paigekeenan , this looks great, except that if an image is wrapped in a `<a>` element, it does not output valid AMP.
To reproduce, drop an image on a page and edit the component properties. In the "Metadata" tab, at the bottom, center a page path as a value for the "Link" field.
Screen Shot 2019-11-06 at 9 49 59 AM

**Comment by paigekeenan** [comment]
@gaetanmarmasse That image wrapping issue is not coming from the AMP image component that I created but actually from the two "Adobe Experience Manager Core Components" images that are embedded on the layout. I wasn't sure where on the layout they were included so I did not delete them from this pr. But ideally, they would pull in the `amp-img` as well.

**Comment by gaetanmarmasse** [comment]
@paigekeenan , are you talking about the Core components logos? 

> To reproduce, drop an image on a page and edit the component properties. In the "Metadata" tab, at the bottom, enter a page path as a value for the "Link" field.

This issue ☝️ is happening when you drop an image component on a page (outside of the logos that are already present).

**Comment by gaetanmarmasse** [comment]
After debugging + pair programming, @paigekeenan and I found where the discrepancy was. Updated the PR and it is ready to merge now.

**Review by gaetanmarmasse — APPROVED** [review]

**Pull request merged**
